### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by manumaticx** [Sitata/titanium_google_plus#3]
I can't get it working on android. The signin method seems to either do nothing or throw an error like this:

```
12-02 13:35:54.236: W/System.err(19605): java.lang.NullPointerException: storage == null
12-02 13:35:54.243: W/System.err(19605):    at java.util.Arrays$ArrayList.<init>(Arrays.java:38)
12-02 13:35:54.243: W/System.err(19605):    at java.util.Arrays.asList(Arrays.java:155)
12-02 13:35:54.243: W/System.err(19605):    at com.sitata.googleplus.TitaniumGooglePlusModule.buildClient(TitaniumGooglePlusModule.java:299)
12-02 13:35:54.243: W/System.err(19605):    at com.sitata.googleplus.TitaniumGooglePlusModule.signin(TitaniumGooglePlusModule.java:339)
12-02 13:35:54.243: W/System.err(19605):    at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
12-02 13:35:54.243: W/System.err(19605):    at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
12-02 13:35:54.243: W/System.err(19605):    at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:908)
12-02 13:35:54.243: W/System.err(19605):    at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1131)
12-02 13:35:54.243: W/System.err(19605):    at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:347)
12-02 13:35:54.243: W/System.err(19605):    at android.os.Handler.dispatchMessage(Handler.java:98)
12-02 13:35:54.243: W/System.err(19605):    at android.os.Looper.loop(Looper.java:135)
12-02 13:35:54.243: W/System.err(19605):    at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
12-02 13:35:54.259: E/TiExceptionHandler(19605): (main) [7429,7429] ----- Titanium Javascript Runtime Error -----
12-02 13:35:54.259: E/TiExceptionHandler(19605): (main) [0,7429] - In alloy/controllers/account/login.js:100,20
12-02 13:35:54.259: E/TiExceptionHandler(19605): (main) [0,7429] - Message: Uncaught Error: storage == null
12-02 13:35:54.259: E/TiExceptionHandler(19605): (main) [0,7429] - Source:             google.signin({
12-02 13:35:54.281: E/V8Exception(19605): Exception occurred at alloy/controllers/account/login.js:100: Uncaught Error: storage == null
```

Any idea what could be the issue?

**Comment by deckameron** [comment]
I am using version 1.5.0 but I am also experiencing this error.

> [WARN] :   W/System.err: java.lang.NullPointerException: storage == null
> [WARN] :   W/System.err: 	at java.util.Arrays$ArrayList.<init>(Arrays.java:38)
> [WARN] :   W/System.err: 	at java.util.Arrays.asList(Arrays.java:155)
> [WARN] :   W/System.err: 	at com.sitata.googleplus.TitaniumGooglePlusModule.buildClient(TitaniumGooglePlusModule.java:296)
> [WARN] :   W/System.err: 	at com.sitata.googleplus.TitaniumGooglePlusModule.signin(TitaniumGooglePlusModule.java:344)
> [WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
> [WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
> [WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:908)
> [WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1131)
> [WARN] :   W/System.err: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:347)
> [WARN] :   W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
> [WARN] :   W/System.err: 	at android.os.Looper.loop(Looper.java:135)
> [WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
> [ERROR] :  TiExceptionHandler: (main) [4471,4471] ----- Titanium Javascript Runtime Error -----
> [ERROR] :  TiExceptionHandler: (main) [0,4471] - In ui/handheld/android/LoginTabGroup/Login.js:105,11
> [ERROR] :  TiExceptionHandler: (main) [0,4471] - Message: Uncaught Error: storage == null
> [ERROR] :  TiExceptionHandler: (main) [0,4471] - Source: 			google.signin({
> [ERROR] :  V8Exception: Exception occurred at ui/handheld/android/LoginTabGroup/Login.js:105: Uncaught Error: storage == null

**Comment by astjohn** [comment]
@deckameron, Can you try building master and let me know what happens?

**Comment by deckameron** [comment]
By building master, you mean compile the module on my machine?

**Comment by astjohn** [comment]
@deckameron - yes, but if that's not possible, don't worry about it. I can eventually do it with a version bump and release, but it will take a while.

**Comment by dyan02** [comment]
i build the master from my machine, everything works fine for android,but why every time i doing the authentication for the first time, the sign in page come twice? thanks

**Comment by astjohn** [comment]
@dyan02, I believe this is an issue regarding the sign in process. Currently, the sign in will perform 2 separate actions under the sign in process. The first thing it does is pull the user's google account credentials and signs in to Google Plus. The second step is that it takes these credentials and then uses AccountManager to create a token for offline use. The token in this case, can then be sent to a server for further processing. I think it will be best to separate these concerns in a future release.

**Comment by mbilwar** [comment]
Hello,

i am new to titanium and i want to Install Mobile Module in my project from this link: https://github.com/manumaticx/titanium_google_plus/tree/android-login  in which @manumaticx  has made some changes. 

How to include this module into my project in titanium using Install Mobile Module?

Thank you in advance :)
